spring:

  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis123
    timeout: 500000 #连接超时时间
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)默认 8
        max-active: 20
        # 连接池最大阻塞等待时间(使用负值表示没有限制)默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 4

server:
  servlet:
    session:
      timeout: 30m #默认30分钟